### ISSUE TITLE
plz help again😭😭

### ISSUE THREAD

**Issue by MaximumX64** [MobilePorting/FNF-PsychEngine-Mobile#136]
### Describe your problem here.

I've wasted my whole day compiling source code and then now at 12 am this happend and now im sad
![image](https://github.com/MobilePorting/FNF-PsychEngine-Mobile/assets/167785527/3e5009c8-7742-4b25-8ef6-6ca050575ba9)
btw i have jdk 17

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

yes but only for that type not found: teacall and project.xml

**Comment by FelipeOchoaL** [comment]
i think you can update your project compileSdkVersion normally there are a lot of problems whit the buil.gradle, i dont think the problem is the jdk 17, but try updating first the android if you search Android Gradle Plugin 7.0.0  and newest versions are compitable with jdk 17 so the problem can be other.
https://stackoverflow.com/questions/69029508/androidx-corecore-ktx1-7-0-depenceny-error-appeared-without-any-modification

**Comment by KarimAkra** [comment]
run these commands
`haxelib remove extension-androidtools`
`haxelib git extension-androidtools https://github.com/MobilePorting/extension-androidtools SAF`

**Comment by MaximumX64** [comment]
im going to try

**Comment by kviks** [comment]
type that in project.xml
<android target-sdk-version="31" />

**Comment by kviks** [comment]
<android target-sdk-version="31" />

**Comment by kviks** [comment]
in ### project.xml add <android target-sdk-version="31" />
