### ISSUE TITLE
Not a question per say, but a request for a feature

### ISSUE THREAD

**Issue by AcrossTheGames** [MobilePorting/FNF-PsychEngine-Mobile#51]
### What is your question?

As stated in the title, this isn't a question, but rather a request for a feature, that feature being the ability to change where the buttons for the notes are located, either as being part of the "Adjust Delay And Combo" section of the options or the "Mobile" options.

My two cents are that some good default options (along side an option for how it is now) would be allow the player to just hit their strumlines notes (though that could mess with some mod charts), allowing 2 sets of arrows (one on each side), or having them displayed along the bottom in a straight line.

**Comment by KarimAkra** [comment]
You can already change your buttons location
When you enter the main options menu press the C button and it'll open a menu with different controls modes for mobile alongside with a customizable mode

And about the other feature you're asking for, "hitting strum notes" instead of the actual buttons
It was done in some web versions of the game and ut was very unplayable so i don't think it's worth trying...
